@startuml

package Model {
}

package Controller {
}

View ..> Controller
View ..> Model

package View {
    boundary SignUpView
        note right of SignUpView
            +signUp(firstName: String, lastName: String, username: String, phone: String, email: String, password: String)
            +showSignUpError(message: String)
        end note

    boundary LoginView
    note right of LoginView
        +login(email: String, password: String)
        +showLoginError(message: String)
    end note

    boundary QuestionsView
    note right of QuestionsView
        +showQuestions(filter: String)
        +logout()
    end note

    boundary QuestionView
    note right of QuestionView
        +showQuestion(questionId: Long)
    end note

    boundary AnswerView
    note right of AnswerView
        +showAnswerForm(questionId: Long)
        +showAnswers(questionId: Long)
    end note

    boundary CommentView
    note right of CommentView
        +showCommentForm(questionId: Long)
        +showComments(questionId: Long)
    end note

    boundary NotificationView
    note right of NotificationView
        +showNotifications(userId: Long)
        +markAsRead(notificationId: Long)
    end note

    boundary TagsView
    note right of TagsView
        +showTags()
    end note

    boundary ProfileView
        note right of ProfileView
            +showProfile(userId: Long)
        end note

    SignUpView ..> LoginView
    LoginView ..> QuestionsView
    QuestionsView ..> QuestionView
    QuestionsView ..> NotificationView
    QuestionsView ..> TagsView
    QuestionsView ..> ProfileView
    QuestionView ..> AnswerView
    AnswerView ..> CommentView
}

@enduml