@startuml

package View {
}

package Controller {
}

View ..> Model
Controller ..> Model

package Model {
    entity UserEntity as UserEntity
    note right of UserEntity
        +getUserId()
        +getFirstName()
        +getLastName()
        +getUserName()
        +getEmail()
        +changePassword(newPassword: String)
    end note

    entity QuestionEntity as QuestionEntity
    note right of QuestionEntity
        +getQuestionId()
        +getTitle()
        +getDescription()
        +incrementViews()
        +updateContent(newTitle: String, newDescription: String)
    end note

    entity AnswerEntity as AnswerEntity
    note right of AnswerEntity
        +getAnswerId()
        +getContent()
        +markAsCorrect()
        +updateContent(newContent: String)
    end note

    entity CommentEntity as CommentEntity
    note right of CommentEntity
        +getCommentId()
        +getReason()
        +updateReason(newReason: String)
    end note

    entity NotificationEntity as NotificationEntity
    note right of NotificationEntity
        +getNotificationId()
        +getMessage()
        +markAsRead()
    end note

    entity TagEntity as TagEntity
        note right of TagEntity
            +getTagId(): Long
            +getQuestions()
        end note

    UserEntity ..> QuestionEntity
    QuestionEntity ..> AnswerEntity
    QuestionEntity ..> TagEntity
    AnswerEntity ..> CommentEntity
    UserEntity ..> NotificationEntity
}


@enduml