@startuml

header Change Password

state " " as s1
state " " as s2
state " " as s3
state "Opened_Profile" as s4
state "Decision" as Decision <<choice>>

Opened_Profile -down-> s1 : User requests to change password
s1 -down-> s2 : System requires current password, new password and repeat new password
s2 -down-> Decision : User provides current password, new password and repeat new password

Decision -down-> s3 : [Ok]
Decision -up-> s1 : [Invalid pattern or new password not matches]

s3 --> s4 : The system shows the updated profile

@enduml