@startuml

header Member Use Case

actor Member

left to right direction

(Login) as UC1
(Logout) as UC2

(Open Profile) as UC4
(Update Profile) as UC5
(Delete Profile) as UC6
(Change Password) as UC36

(Create Question) as UC8
(Delete MyQuestion) as UC9
(Update Question) as UC10
(Open Questions) as UC11
(Open MyQuestion) as UC12
(Open MyQuestions) as UC13

(Create Answer) as UC14
(Update Answer) as UC15
(Delete MyAnswer) as UC16
(Mark Answer as Correct) as UC17

(Create Comment) as UC18
(Update Comment) as UC19
(Delete MyComment) as UC20
(Open Notifications) as UC33
(Open Notification) as UC34

(Update Tag) as UC21

(Restore Password) as UC37

UC8 .-up-> UC11 : <<extend>>
UC12 .-up-> UC13 : <<extend>>
UC9 .-up-> UC12 : <<extend>>
UC10 .-up-> UC12 : <<extend>>

UC21 .-up-> UC8 : <<extend>>
UC21 .-up-> UC10 : <<extend>>

UC5 .-up-> UC4 : <<extend>>
UC6 .-up-> UC4 : <<extend>>
UC36 .-up-> UC5 : <<extend>>

UC15 .-up-> UC14 : <<extend>>
UC16 .-up-> UC14 : <<extend>>

UC19 .-up-> UC18 : <<extend>>
UC20 .-up-> UC18 : <<extend>>
UC33 .-down-> UC34 : <<extend>>

UC13 .-up-> UC4 : <<extend>>


Member --> UC1
Member --> UC2
Member --> UC4
Member --> UC11
Member --> UC14
Member --> UC17
Member --> UC18
Member --> UC33
Member --> UC37

@enduml