@startuml

header Use Case

actor Guest
actor Member
actor Admin

Guest <|-down- Member
Member <|-down- Admin

left to right direction

(Login) as UC1
(Logout) as UC2
(Sign Up) as UC3
(Open Profile) as UC4
(Update Profile) as UC5
(Delete Profile) as UC6
(Open Question) as UC7
(Create Question) as UC8
(Delete MyQuestion) as UC9
(Update Question) as UC10
(Open Questions) as UC11
(Filter Questions) as UC12
(Open MyQuestions) as UC13
(Create Answer) as UC14
(Update Answer) as UC15
(Delete MyAnswer) as UC16
(Mark Answer as Correct) as UC17
(Create Comment) as UC18
(Update Comment) as UC19
(Delete Comment) as UC20
(Update Tag) as UC22
(Delete Tag) as UC24
(Search Content) as UC25
(Open Tags) as UC26
(Search Tags) as UC27
(Delete Question) as UC28
(Create User) as UC29
(Open Users) as UC30
(Delete Answer) as UC31
(Open Notifications) as UC33
(Open Notification) as UC34
(Change Password) as UC36
(Restore Password) as UC37

Guest --> UC7
Guest --> UC11
Guest --> UC25
Guest --> UC26
Guest --> UC27
Guest --> UC3

Member --> UC1
Member --> UC2
Member --> UC4
Member --> UC5
Member --> UC6
Member --> UC8
Member --> UC9
Member --> UC10
Member --> UC12
Member --> UC13
Member --> UC14
Member --> UC15
Member --> UC16
Member --> UC17
Member --> UC18
Member --> UC19
Member --> UC20
Member --> UC22
Member --> UC33
Member --> UC34
Member --> UC36
Member --> UC37

Admin --> UC24
Admin --> UC28
Admin --> UC29
Admin --> UC30
Admin --> UC31

@enduml