@startuml

header Guest Use Case

actor Guest

left to right direction

(Sign Up) as UC3

(Open Question) as UC7
(Open Questions) as UC11
(Filter Questions) as UC12

(Search Content) as UC25
(Open Tags) as UC26
(Search Tags) as UC27

UC7 .-up-> UC11 : <<extend>>
UC12 .-up-> UC11 : <<extend>>
UC25 .-up-> UC11 : <<extend>>
UC27 .-up-> UC26 : <<extend>>

Guest --> UC11
Guest --> UC3
Guest --> UC26

@enduml