@startuml

header User Open Question

state "Opened Questions" as s3
state " " as s4
state "Opened Question" as s5

s3 -down-> s4 : User requires to read one Question
s4 -down-> s5 : System allows User to read one Question

@enduml