@startuml

header User Open Tags

state "Access Application" as s1
state "Access Tags" as s2
state "Tags" as s3

[*] -down-> s1 : User access the system
s1 -down-> s2 : User request to access Tags
s2 -down-> s3 : System shows Tags

@enduml