@startuml

header Admin Open Users

state "Login" as s1
state " " as s2
state "Users" as s3
state "Decision" as Decision <<choice>>


[*] --> s1 : Admin initializes the system

s1 --> s2 : System validates Admin
s2 -down-> Decision : System check credentials
Decision -down-> s3 : [OK]
Decision -down-> s1 : [Failed]

@enduml