@startuml

header Admin Context Diagram

[*] --> Initial

Initial --> Opened_Questions: Login

Opened_Questions --> Opened_Dashboard : Open Dashboard
Opened_Questions --> Opened_Question : Open Question
Opened_Question --> Opened_Question : Delete Question \n Delete Answer
Opened_Questions --> Final : Logout
Opened_Question --> Final : Logout

Opened_Dashboard --> Opened_Dashboard : Open Users \n Create User \n Delete Tag
Opened_Dashboard --> Final : Logout

Final --> [*]

@enduml