@startuml
[*] --> Login

skinparam dpi 150
skinparam direction top-down

state "Insert Credentials" as InsertCredentials
state "Sign In" as SignIn
state "Check Credentials" as CheckCredentials

Login -down-> InsertCredentials
Login -right-> SignIn


InsertCredentials -left-> Email
InsertCredentials -left-> Password


Email -down-> CheckCredentials
Password -down-> CheckCredentials

CheckCredentials -down-> [*] : Success
CheckCredentials -left-> Login : Failure

@enduml