@startuml

header Admin Delete Tag

state "Opened Dashboard" as s1
state " " as s2
state "Deleted Tag" as s4
state "Decision" as Decision <<choice>>

[*] --> s1 : The System shows Opened Dashboard
s1 -down-> s2 : Admin requests to delete Tag
s2 -down-> Decision : The System requires confirmation
Decision -down-> s4 : [OK]
Decision -down-> s1 : [Cancel]

@enduml