@startuml

Forum *-down-> "*" User
Forum *-down-> "*" Notification
Forum *-down-> "*" Question
User *-down-> Profile
User .-left-> Role
Question *-down-> "*" Answer
Question "*" o-down-> "0..*" Category
Category *-down-> "*" SubCategory
Answer *-down-> "*" Comment


class User {
- id*: Long
- firstName: String
- lastName: String
- email: String
- password: String
- role: Role
}

enum Role {
- ADMIN
- CUSTOMER
- GUEST
}

class Profile {
- id*: Long
- name: String
- bio: String
}

class Question {
- id*: Long
- title: String
- description: String
- date: LocalDateTime
- user: String
- views: Integer
}

class Answer {
- id*: Long
- content: String
- date: LocalDateTime
- user: String
- isCorrect: Boolean
}

class Comment {
- id*: Long
- reason: String
- date: LocalDateTime
- user: String
}

class Category {
- id*: Long
- message: String
- subCategory: List<SubCategory>
}

class SubCategory {
- id*: Long
- message: String
}

class Notification {
- id*: Long
- message: String
- date: LocalDateTime
- wasRead: Boolean
- user: String
}

@enduml