@startuml

left to right direction

actor User

package View {
    [QuestionView]
    [AnswerView]
}

package Controller {
    [AnswerController]
}

package Model {
    [AnswerEntity]
    [QuestionEntity]
}

User --> [QuestionView] : 1 : openQuestion(questionId)
[QuestionView] -right-> [AnswerView] : 2 : showAnswerForm()
User --> [AnswerView] : 3 : writeAnswer(content)
[AnswerView] --> [AnswerController] : 4 : createAnswer(questionId, content)

[AnswerController] --> [QuestionEntity] : 5 : findQuestionById(questionId)
[AnswerController] --> [AnswerEntity] : 6 : create(content, user, date)
[AnswerEntity] -right-> [QuestionEntity]

@enduml
