@startuml

left to right direction

actor User

package View {
  [LoginView]
  [QuestionsView]
}

package Controller {
  [LoginController]
}

package Model {
    [UserModel]
}

User --> [LoginView] : 1 : login(email, password)
User --> [QuestionsView] : 4 : updateView()
[LoginView] --> [LoginController] : 2 : login(email, password)
[LoginController] --> [UserModel] : 3 findByEmail(email)


@enduml