@startuml

left to right direction

actor User

package View {
  [LoginView]
}

package Controller {
  [LoginController]
}

package Model {
}

User --> [LoginView] : 1 : login(email, password)
[LoginView] --> [LoginController] : 1 login(email, password)


@enduml