@startuml

left to right direction

actor User

package View {
    [LoginView]
    [RestorePasswordView]
}

package Controller {
    [UserController]
}

package Model {
    [UserEntity]
}

User --> [RestorePasswordView] : 1 : requestRestorePassword()
[RestorePasswordView] --> [UserController] : 2 : sendResetToken(email)
[UserController] --> [UserController] : 3 : generateResetToken(email) \n 7 : validateToken(token)
[UserController] --> User : 4 : sendResetLink(email, token)

User --> [RestorePasswordView] : 5 : enterNewPassword()
[RestorePasswordView] --> [UserController] : 6 : restorePassword(token, newPassword)
[UserController] --> [UserEntity] : 8 : updatePassword(newPassword)
[RestorePasswordView] -right-> [LoginView] : 9 : redirectToLogin()

@enduml
