@startuml

header Delete Question

state " " as s1
state " " as s2
state "Decision" as Decision <<choice>>

Opened_Question -down-> s1 : Admin requests to delete Question
s1 -down-> Decision : System requires confirmation
Decision -down-> s2 : [OK]
Decision -up-> Opened_Question : [Cancel]

s2 -down-> Opened_Questions : System deletes the question and answers and comments associated

@enduml