@startuml

header Restore Password

state " " as s1
state " " as s2
state " " as s3
state "Login" as s4
state "Decision" as Decision <<choice>>

Login -down-> s1 : User requests to restore password
s1 -down-> s2 : System requires email
s2 -down-> Decision : User provides email

Decision -down-> s3 : [Ok]
Decision -up-> s1 : [Invalid email]

s3 --> s4 : The system provides reset password id

@enduml